---

- name: Naive assertion for ansible_service_mgr (fail on unsupported init systems)
  assert:
    that:
      - ansible_service_mgr == "systemd"
    fail_msg: "this role work only with systemd distributives"

- name: Naive assertion for alertmanager_bot_telegram_token
  assert:
    that:
      - item['value']['telegram_token'] != "example"
    fail_msg: "alertmanager_bot_telegram_token is required"
  loop: "{{ alertmanager_bots | dict2items }}"

- name: Naive assertion for alertmanager_bot_telegram_admins
  assert:
    that:
      - alertmanager_bots|length > 0
    fail_msg: "alertmanager_bots must not be empty"
